[package]
name = "bkb"
version = "1.0.6"
edition = "2024"
description = "Booklet Builder"

[dependencies]
image = "0.25"
native-dialog = {version = "0.9.6"}
# rfd = "0.17"
# timed-map= "1.7"


[dependencies.lopdf]
version = "0.44"

[dependencies.slint]
version = "1.17"

default-features = false
features = [
    "std",
    "accessibility",
    "compat-1-2",
    "backend-winit",
    "renderer-femtovg",
    "unstable-winit-030"]
# [target.'cfg(windows)'.dependencies]
# windows = { version = "0.62", features = [
#     "Win32_UI_WindowsAndMessaging",
#     "Win32_System_LibraryLoader",
#     "Win32_Foundation"
# ]}

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
cc = { version = "1.4.6", optional = true }


[features]
win8 = ["dep:cc"]

[package.metadata.winresource]
# OriginalFilename = "bkb.exe"
LegalCopyright = "Copyright © 2026 Kaay"
FileDescription = "小册子生成工具"
ProductName = "小册子生成工具"

[build-dependencies]
slint-build = "1.17"
lucide-slint = "1.8.0"
# thunk-rs = { version = "0.3.5", default-features = false , features = ["win7", "lib", "subsystem_windows"] }
# twill = { version = "0.2", features = ["slint"] }


[profile.dev.package."*"]
opt-level = "z"
codegen-units = 1

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
strip = true
panic = "abort"
